<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\DTOs\" />
    <Folder Include="Features\Authentication\Mapping\" />
    <Folder Include="Features\Authentication\Validators\" />
    <Folder Include="Features\Authentication\Queries\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Interfaces\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartClinic.Domain\SmartClinic.Domain.csproj" />
  </ItemGroup>

</Project>
